In [1]:
import pandas as pd

In [11]:
#merge and join data
df_customers=pd.DataFrame({
    "customer_id":[1,2,3,4],
    "name":["Bob","Adam","Joy","Dave"],
})

df_order=pd.DataFrame({
    "order_id":[101,102,103,104],
    "customer_id":[2,1,4,5],
    "amount":[250,120,300,180]
    
})
pd.merge(df_customers,df_order , on="customer_id") #Inner join
pd.merge(df_customers,df_order , on="customer_id", how="left") #left join
pd.merge(df_customers,df_order , on="customer_id",how="right") #right join
pd.merge(df_customers,df_order , on="customer_id",how="outer")  #outer join

   customer_id  name  order_id  amount
0            1   Bob     102.0   120.0
1            2  Adam     101.0   250.0
2            3   Joy       NaN     NaN
3            4  Dave     103.0   300.0
4            5   NaN     104.0   180.0

In [5]:
df_customers

   customer_id  name
0            1   Bob
1            2  Adam
2            3   Joy
3            4  Dave

In [7]:
df_order

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [16]:
# Concatenation of data
df1=pd.DataFrame({
    "customer_id":[1,2,3,4],
    "name":["Bob","Adam","Joy","Dave"],
})

df2=pd.DataFrame({
    "customer_id":[4,5,8,7],
    "name":["A","B","C","D"],
})

pd.concat([df1,df2]) #row wise
pd.concat([df1,df2],ignore_index=True) 

pd.concat([df1,df2],axis=1)  #column wise

   customer_id  name  customer_id name
0            1   Bob            4    A
1            2  Adam            5    B
2            3   Joy            8    C
3            4  Dave            7    D