In [1]:
import pandas as pd

In [3]:
info={
    "Name": ["Bidisha", "Rahul", "Jaya"],
    "CGPA": [9.00,8.7,7.5]
}
df=pd.DataFrame(info)
print(df)

      Name  CGPA
0  Bidisha   9.0
1    Rahul   8.7
2     Jaya   7.5

In [4]:
df

      Name  CGPA
0  Bidisha   9.0
1    Rahul   8.7
2     Jaya   7.5

In [8]:
#series creation
s=pd.Series([1,2,3,4,5])
print(s)
print(type(s))

#index
print(s[2])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>
3

In [11]:
#custom label
s=pd.Series([12,28,34,49,50],index=["A","B","C","D","E"])
print(s)
print(s["C"])
print(s.index)

A    12
B    28
C    34
D    49
E    50
dtype: int64
34
Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [5]:
#series 
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])

print(s1*s2)
s1[0]=100
changed_s1=s1.drop(0)

print(s1)
print(changed_s1)

0     10
1     40
2     90
3    160
4    250
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
#Dataframe
#Creating from dictionary
info={
    "Name": ["Bidisha","John","Bob"],
    "Age":[23,34,56],
    "CGPA": [9.00,8.7,7.5]
    
}

df=pd.DataFrame(info)
print(df)

print(df.index)
print(df.columns)

      Name  Age  CGPA
0  Bidisha   23   9.0
1     John   34   8.7
2      Bob   56   7.5
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [10]:
df

      Name  Age  CGPA
0  Bidisha   23   9.0
1     John   34   8.7
2      Bob   56   7.5

In [11]:
#creating from list of lists
df=pd.DataFrame([["Joy",23],["Bob",56],["Adam",10]] , columns=["Name","Age"])
print(df)

   Name  Age
0   Joy   23
1   Bob   56
2  Adam   10

In [12]:
#creating from numpy arrays
import numpy as np
np_arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(np_arr, columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [19]:
import os
os.getcwd()

'C:\\Users\\Bidisha Das\\OneDrive\\Desktop\\prime classes\\Pandas'

In [20]:
os.listdir()

['.ipynb_checkpoints',
 'employee_data.csv',
 'employee_data.json',
 'pandas_tutorial.ipynb']

In [31]:
#csv data
df=pd.read_csv("employee_data.csv")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [47]:
#dataframe methods
df.head() #starting 5 rows
df.tail(2) #last 2 rows
df.sample() #random rows

df.info() #gives info about the dataframe
df.shape #returns a tuple of(rows,columns)
df.describe() #works on numerical data
df.columns
df.nunique() #returns total number of unique rows

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [36]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [2]:
#AQI data set
df=pd.read_csv("globalAirQuality.csv")
print(df)

                        timestamp country      city  latitude  longitude  \
0      2025-11-04 18:25:17.554219      US  New York    40.713    -74.006
1      2025-11-04 19:25:17.554219      US  New York    40.713    -74.006
2      2025-11-04 20:25:17.554219      US  New York    40.713    -74.006
3      2025-11-04 21:25:17.554219      US  New York    40.713    -74.006
4      2025-11-04 22:25:17.554219      US  New York    40.713    -74.006
...                           ...     ...       ...       ...        ...
17995  2025-11-19 13:25:17.554219      CH    Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH    Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH    Zurich    47.377      8.542
17998  2025-11-19 16:25:17.554219      CH    Zurich    47.377      8.542
17999  2025-11-19 17:25:17.554219      CH    Zurich    47.377      8.542

         pm25     pm10     no2    so2      o3     co  aqi  temperature  \
0      50.295  108.938  27.998  6.539  52.568  1.096  108       18.504
1      32.083   63.043  36.120  4.021  43.536  1.075   90        5.838
2      42.250   82.553  26.935  9.538  23.320  0.977   84       31.833
3      30.403   79.951  63.536  7.609  31.369  0.230  158       23.140
4      21.083   66.423  38.997  6.919  45.615  1.085   97       13.632
...       ...      ...     ...    ...     ...    ...  ...          ...
17995  27.899   74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950   47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347   72.908  46.976  5.763  66.492  0.947  122       21.951
17998  40.722   95.152  32.957  5.524  53.193  0.868   95       24.042
17999  25.830   30.411  35.317  4.336  66.246  0.848   88        8.529

       humidity  wind_speed
0        70.168       3.725
1        80.088       8.969
2        62.783       9.650
3        89.153       8.956
4        76.499       4.017
...         ...         ...
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660
17998    31.880       2.642
17999    59.104       4.403

[18000 rows x 15 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    18000 non-null  object
 1   country      18000 non-null  object
 2   city         18000 non-null  object
 3   latitude     18000 non-null  float64
 4   longitude    18000 non-null  float64
 5   pm25         18000 non-null  float64
 6   pm10         18000 non-null  float64
 7   no2          18000 non-null  float64
 8   so2          18000 non-null  float64
 9   o3           18000 non-null  float64
 10  co           18000 non-null  float64
 11  aqi          18000 non-null  int64
 12  temperature  18000 non-null  float64
 13  humidity     18000 non-null  float64
 14  wind_speed   18000 non-null  float64
dtypes: float64(11), int64(1), object(3)
memory usage: 2.1+ MB

In [4]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000